# Generated by Django 5.1.7 on 2025-05-12 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('last2', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='tittle',
            new_name='title',
        ),
    ]
